# Generated by Django 4.2.25 on 2025-10-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(choices=[('NA', 'North America'), ('SA', 'South America'), ('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('OC', 'Oceania'), ('ME', 'Middle East'), ('CA', 'Central America'), ('CAR', 'Caribbean')], default='NA', max_length=3),
            preserve_default=False,
        ),
    ]
