# Generated by Django 4.2.25 on 2025-10-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviepetition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepetition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
